### ISSUE TITLE
您太小看携程的反扒技术了

### ISSUE THREAD

**Issue by bearllm** [icmpnorequest/Ctrip-Price-Crawl#1]
我研究了半天携程的http://hotels.ctrip.com/domestic/cas/oceanball，也得到了eleven参数，但是请求回来的HTML数据，还是是蜜罐数据，价格和真实价格根本对不上

**Comment by icmpnorequest** [comment]
写这个代码的主要目的是为了锻炼获取数据的能力，并无任何商业目的。携程的反爬做的很好，有Bot Detection、Browser Fingerprinting技术等，还有您说的Hoenypot技术。另外，eleven参数破解方法已失效，如果您有解决反爬的方法，欢迎与我沟通。
